name: Confluent IaC CI Workflow

on:
  pull_request:
    paths:
      - '**/topics/*.yaml'

jobs:
  detect-changes:
    name: Detect Changed Topics
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Get list of changed topic files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: '**/topics/*.yaml'

      - name: Build matrix with env and cloud
        id: set-matrix
        run: |
          echo "Building matrix..."

          files_json=$(echo '${{ steps.changed-files.outputs.all_changed_files }}' | jq -R 'split(" ") | map(select(length > 0))')

          echo "Changed files:"
          echo "$files_json" | jq .

          matrix_entries=$(jq -n --argjson files "$files_json" '
            {
              include: [ 
                $files[] | 
                {
                  file: .,
                  cloud: (split("/")[0]),
                  env: (split("/")[1])
                }
              ]
            }
          ')

          echo "Full matrix JSON:"
          echo "$matrix_entries" | jq .

          # Safely write to $GITHUB_OUTPUT
          echo "matrix=$(echo "$matrix_entries" | jq -c .)" >> "$GITHUB_OUTPUT"

  terragrunt-plan:
    name: Terragrunt Plan
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.detect-changes.outputs.matrix)}}
    environment: ${{ matrix.env }}

    steps:
      - uses: actions/checkout@v4

      - name: Set base environment variables
        run: |
          echo "CLOUD_PROVIDER=${{ matrix.cloud }}" >> $GITHUB_ENV
          echo "ENV=${{ matrix.env }}" >> $GITHUB_ENV
          echo "DIR_PATH=$(dirname ${{ matrix.file }})" >> $GITHUB_ENV
          echo "FILE_NAME=$(basename ${{ matrix.file }})" >> $GITHUB_ENV

      - name: Set cloud-specific environment secrets
        run: |
          echo "Setting env for: ${{ matrix.cloud }}"

          if [[ "${{ matrix.cloud }}" == "azure" ]]; then
            echo "CONFLUENT_API_KEY=${{ secrets.CONFLUENT_API_KEY }}" >> $GITHUB_ENV
            echo "CONFLUENT_API_SECRET=${{ secrets.CONFLUENT_API_SECRET }}" >> $GITHUB_ENV
            echo "KAFKA_API_KEY=${{ secrets.KAFKA_API_KEY }}" >> $GITHUB_ENV
            echo "KAFKA_API_SECRET=${{ secrets.KAFKA_API_SECRET }}" >> $GITHUB_ENV
            echo "KAFKA_CLUSTER_ID=${{ secrets.KAFKA_CLUSTER_ID }}" >> $GITHUB_ENV
            echo "KAFKA_REST_ENDPOINT=${{ secrets.KAFKA_REST_ENDPOINT }}" >> $GITHUB_ENV
            echo "AZURE_RESOURCE_GROUP_NAME=${{ secrets.AZURE_RESOURCE_GROUP_NAME }}" >> $GITHUB_ENV
            echo "AZURE_STORAGE_ACCOUNT_NAME=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_ENV
            echo "AZURE_CONTAINER_NAME=${{ secrets.AZURE_CONTAINER_NAME }}" >> $GITHUB_ENV
            echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
            echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
            echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
            echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
          elif [[ "${{ matrix.cloud }}" == "gcp" ]]; then
            echo "CONFLUENT_API_KEY=${{ secrets.CONFLUENT_API_KEY }}" >> $GITHUB_ENV
            echo "CONFLUENT_API_SECRET=${{ secrets.CONFLUENT_API_SECRET }}" >> $GITHUB_ENV
            echo "KAFKA_API_KEY=${{ secrets.KAFKA_API_KEY }}" >> $GITHUB_ENV
            echo "KAFKA_API_SECRET=${{ secrets.KAFKA_API_SECRET }}" >> $GITHUB_ENV
            echo "KAFKA_CLUSTER_ID=${{ secrets.KAFKA_CLUSTER_ID }}" >> $GITHUB_ENV
            echo "KAFKA_REST_ENDPOINT=${{ secrets.KAFKA_REST_ENDPOINT }}" >> $GITHUB_ENV
            echo "GOOGLE_CREDENTIALS=${{ secrets.GOOGLE_CREDENTIALS }}" >> $GITHUB_ENV
            echo "GCP_BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME }}" >> $GITHUB_ENV
          elif [[ "${{ matrix.cloud }}" == "aws" ]]; then
            echo "CONFLUENT_API_KEY=${{ secrets.CONFLUENT_API_KEY }}" >> $GITHUB_ENV
            echo "CONFLUENT_API_SECRET=${{ secrets.CONFLUENT_API_SECRET }}" >> $GITHUB_ENV
            echo "KAFKA_API_KEY=${{ secrets.KAFKA_API_KEY }}" >> $GITHUB_ENV
            echo "KAFKA_API_SECRET=${{ secrets.KAFKA_API_SECRET }}" >> $GITHUB_ENV
            echo "KAFKA_CLUSTER_ID=${{ secrets.KAFKA_CLUSTER_ID }}" >> $GITHUB_ENV
            echo "KAFKA_REST_ENDPOINT=${{ secrets.KAFKA_REST_ENDPOINT }}" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
            echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
            echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> $GITHUB_ENV
          else
            echo "Unsupported cloud provider: ${{ matrix.cloud }}"
            exit 1
          fi

      - name: Print all environment variables
        run: env
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Install Terragrunt
        run: |
          wget -q https://github.com/gruntwork-io/terragrunt/releases/download/v0.56.3/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Terragrunt Init
        working-directory: ${{ env.DIR_PATH }}
        run: terragrunt init

      - name: Terragrunt Validate
        working-directory: ${{ env.DIR_PATH }}
        run: terragrunt validate

      - name: Terragrunt Plan
        working-directory: ${{ env.DIR_PATH }}
        run: terragrunt plan
        
